import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./styles.css";
import AuthProvider from "@/components/providers/AuthProvider";
import ThemeProvider from "@/components/providers/ThemeProvider";
import { ApolloWrapper } from "@/lib/apollo-wrapper";
import { getServerSession } from "next-auth/next";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { authOptions } from "@/app/api/auth/authOptions";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "4Fact Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const session = await getServerSession(authOptions);

    return (
        <html lang="en" suppressHydrationWarning>
            <head>
                <link rel="icon" href="/images/4fact.svg" />
            </head>
            <body className={`${inter.className} bg-gray-50 dark:bg-gray-900 `}>
                <AuthProvider session={session}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                    >
                        <ApolloWrapper>{children}</ApolloWrapper>
                        <ToastContainer />
                    </ThemeProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
